// Appeal report helper utilities
// -----------------------------------------------------------------------------
// The actual appeal report PDF is now generated by DetailedAppraisalGrid and
// uploaded to the `appeal-reports` Supabase Storage bucket. The Appeal Log
// downloads that PDF on demand and (optionally) appends the imported PowerComp
// photo packet using pdf-lib.
//
// The previous standalone cover-page builder lived here. It produced a fake
// 1-page cover when no real report existed; that path has been retired in
// favor of the round-trip with the Detailed tab. Only the small, framework-
// agnostic helpers (single PDF download, zip-of-PDFs download, filename
// sanitization) remain — they are used by the per-row print and Batch Print
// actions in AppealLogTab.

/**
 * Trigger a browser download for a Uint8Array PDF.
 */
export function downloadPdf(bytes, filename) {
  const blob = new Blob([bytes], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Build a zip of multiple Appeal Report PDFs (one per subject) and trigger a
 * download. JSZip is dynamically imported so it doesn't inflate the initial
 * bundle.
 */
export async function downloadAppealReportsZip(reports, zipFilename) {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  for (const r of reports) {
    zip.file(r.filename, r.bytes);
  }
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = zipFilename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Sanitize a filename — keep it filesystem safe across OSes.
 */
export function safeFilenamePart(s) {
  return String(s || '')
    .replace(/[\\/:*?"<>|\r\n\t]+/g, '_')
    .replace(/\s+/g, '_')
    .slice(0, 80);
}
